/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/


--Total number of customers BY country
SELECT country, COUNT(customer_key) AS Customers_By_Country
FROM gold.dim_customers
GROUP BY country
ORDER BY Customers_By_Country DESC;

--Total Customers BY Gender
SELECT gender,COUNT(customer_key) AS Customers_By_Gender
FROM gold.dim_customers
GROUP BY gender
ORDER BY Customers_By_Gender DESC;

--Total Products By Category
SELECT category, COUNT(product_key) AS Products_By_Category
FROM gold.dim_products
GROUP BY category
ORDER BY Products_By_Category DESC;

--Average Cost by Category
SELECT category, AVG(cost) AS Avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY Avg_cost DESC;

--Total revenue generated by each category
SELECT  p.category, SUM(s.sales_amount) AS Total_Revenue
FROM gold.fact_sales s
LEFT JOIN gold.dim_products p
ON s.product_key=p.product_key
GROUP BY p.category
ORDER BY Total_Revenue DESC

--Total revenue generated by each customer
SELECT c.customer_key,c.first_name,c.last_name AS Customer, SUM(s.sales_amount) AS Total_Revenue
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c
ON s.customer_key=c.customer_key
GROUP BY c.customer_key,c.first_name,c.last_name
ORDER BY Total_Revenue DESC

--Distribution of sold Items across countries
SELECT c.country, SUM(s.quantity) AS Total_sold_Items
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c
ON s.customer_key=c.customer_key
GROUP BY c.country
ORDER BY Total_sold_Items DESC

